taxjar/taxjar-woocommerce-plugin

- includes/class-wc-taxjar-integration.php
- tests/bootstrap.php
- tests/specs/test-actions.php
- tests/specs/test-filters.php
Fixed a simple math bug that was causing an error in displaying the correct tax amount on checkout page.
Added a new spec to prove the bug and fix.
> Hotfix for shipping tax calculations

- includes/class-wc-taxjar-integration.php
- taxjar-woocommerce.php
WooCommerce 2.5 changed how rates were cached, moving from transients to wp_cache.  This branch adds support for removing new cached rates if integrated with WooCommerce V2.5 or the previous functionality if on integrated with an older version.
To keep up with best practiced I have also updated how API responses are cached to now use wp_cache.
> WooCommerce 2.5 compatibility

- includes/class-wc-taxjar-download-orders.php
- includes/class-wc-taxjar-integration.php
Hi all,
This PR contains a fix for an API error that was being raised when shipping is disabled.  I also changed the connection code to use home_url() rather than site_url().  This has been tested by completing orders in the following scenarios:
- Purchased a physical product with shipping turned off.
- Purchased a virtual product which has shipping disabled.
- Purchased a physical product with shipping turned on.
I tested this using the latest version of WordPress (4.5.3) and the latest version of WooCommerce (2.6.1)
> properly handle when shipping is disabled in WooCommerce

- CHANGELOG.md
- includes/class-wc-taxjar-ajax.php
- includes/class-wc-taxjar-integration.php
- includes/class-wc-taxjar-nexus.php
- includes/js/wc-taxjar-admin.js
- readme.txt
- taxjar-woocommerce.php
- tests/specs/test-class-taxjar-nexus.php
Hi all,
This PR caches the nexus region response and references to ensure that an order's ship to country/state are actually in the nexus list before making an API call for a tax calculation.  I have done quite a bit of testing on this and will do more tonight and tomorrow but wanted to get a PR up for people to start reviewing.
> TJ-1224 limit API calls to nexus areas

- includes/class-wc-taxjar-download-orders.php
- includes/class-wc-taxjar-nexus.php
- tests/specs/test-class-taxjar-nexus.php
This PR does a few things:
- Change `get_currentuserinfo()` to `wp_get_current_user()`. The former is being deprecated.
- Account for more return types of the `wc_taxjar_nexus_list` transient. Previously, it would use the transient value even if the transient value was "falsy" - like an empty array.
- Add tests for the various transient checks, including a shorter cache timeout period.
> Add fallback for empty/false/otherwise wrong nexus list

- taxjar-woocommerce.php
WooCommerce recommends [displaying an admin notice](https://docs.woocommerce.com/document/create-a-plugin/#section-27) for service integration plugins such as TaxJar. This PR adds a notice if a TaxJar API token isn't yet provided:
> Installation Notice for Connecting to TaxJar

- includes/class-wc-taxjar-integration.php
If local pickup is selected, tax isn't collected at the store's origin city and postal code. This PR fixes the conditional check to more closely resemble WC_Customer's `get_taxable_address` code by using `wc_get_chosen_shipping_method_ids()`. It also drops the virtual order check, don't think it's necessary when we're just checking for local pickup. Filter spec passing.
> Fix Calculations for Local Pickups

- includes/class-wc-taxjar-integration.php
- includes/tlc-transients/class-tlc-transient-update-server.php
- includes/tlc-transients/class-tlc-transient.php
- includes/tlc-transients/functions.php
- includes/tlc-transients/tlc-transients.php
- tests/bootstrap.php
- tests/framework/customer-helper.php
- tests/framework/product-helper.php
- tests/framework/woocommerce-helper.php
- tests/specs/test-actions.php
This PR passes line items to SmartCalcs rather than the overall amount, so everything plays nicely with WooCommerce Subscriptions. The subscription plugin calls `woocommerce_calculate_totals` with only the subscription-based products, making another request to SmartCalcs.
In addition, this allows us to exempt line items if they aren't taxable and paves the way for product taxability. Tax should also be saved for each individual line item.
Lastly, drops the old `woocommerce_ajax_calc_line_taxes` filter.
> Line Item Taxability & Improved API Request Caching

- includes/class-wc-taxjar-integration.php
- tests/bootstrap.php
- tests/framework/coupon-helper.php
- tests/framework/customer-helper.php
- tests/framework/product-helper.php
- tests/framework/woocommerce-helper.php
- tests/specs/test-actions.php
- tests/specs/test-activation.php
- tests/specs/test-class-taxjar-nexus.php
- tests/specs/test-filters.php
- tests/specs/test-settings.php
This PR supports product exemptions based on user-defined tax classes and codes:
For example, if a product is assigned to the "Clothing - 20010" tax class:
Sales tax won't be collected in certain jurisdictions of NY for products assigned to this tax class:
**Important**: These tax classes are user-defined and it's up to the user to find the correct tax code in our documentation. Woo's additional tax classes is just a `textarea` box.
> Product Taxability

- includes/class-wc-taxjar-integration.php
Fixes local pickup error with `wc_get_chosen_shipping_method_ids()` in WooCommerce < 2.6.2.
> Local Pickup WooCommerce < 2.6.2 Compatibility

- includes/class-wc-taxjar-integration.php
This PR will only calculate tax on subscriptions when a recurring payment occurs. If a subscription has a trial period, the line subtotal is $0. Check both the unit price **and** line subtotal before adding line items to an API calculation.
> Fix Subscription Calculations at Checkout

- includes/class-wc-taxjar-integration.php
WooCommerce 3.0 removed the previous hook we were using for handling backend order calculations via the "Calculate Tax" / "Recalculate" button: `woocommerce_ajax_calc_line_taxes`. Luckily, there's another hook available called `woocommerce_before_save_order_items` for both 2.6 and 3.0. More info on this here: https://wordpress.org/support/topic/woocommerce-3-0-missing-hook-woocommerce_ajax_calc_line_taxes/
This PR also improves native rate handling for multiple product tax classes for exemptions. If two different tax classes are used in an order, multiple tax columns will be added:
> Backend Order Calculations for Woo 2.6 & 3.0

- includes/class-wc-taxjar-integration.php
WooCommerce 3.1 has an odd way of handling "limit usage to X items" discounts. Inside `class-wc-coupon.php`, the limit usage quantity is reduced during the calculation process when obtaining the discounted price. Once TaxJar hooks into the calculation process, the limit usage quantity is already reduced to zero. This PR resets the limit usage quantity based on the coupon metadata so we can ensure tax isn't collected if the quantity threshold is reached.
WooCommerce 3.2 deprecates the `get_discounted_price` method in `class-wc-cart.php` and removes the code used to determine "limit usage to X items" for `get_discount_amount` in `class-wc-coupon.php`, so we need to test this functionality and ensure it's backwards-compatible in a future 3.2 beta.
WooCommerce 3.2 also introduces coupons / …
> Fix "limit usage to X items" discounts in WooCommerce 3.1

- taxjar-woocommerce.php
This PR resolves the following issue when another plugin globally declares `plugin_settings_link()`:
```
Fatal error: Cannot redeclare plugin_settings_link()
```
> Fix cannot redeclare plugin_settings_link()

- includes/class-wc-taxjar-integration.php
Since WooCommerce 3.2 revamped the calculation process to calculate totals before we can create a tax rate based on our API response, we need a way to modify the grand total without having to re-calculate for brand new rates introduced in the system.
This PR adds a new hook for the `woocommerce_calculated_total` filter and only updates the grand total if the subtotal is equal to grand total and tax is returned from SmartCalcs.
> Modify order total if missing tax in WooCommerce 3.2+

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
We've seen various edge cases with 3rd party plugins manipulating totals, such as order-level discounts causing issues with how TaxJar adds sales tax to the grand total.
Instead of using `woocommerce_calculated_total`, leverage `woocommerce_after_calculate_totals` in WooCommerce 3.2 and re-calculate for new tax rates introduced in the system.
> Recalculate totals in WooCommerce 3.2 instead of manually updating total

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
If a merchant has origin-based or CA modified-origin sourcing, our plugin could find a different native tax rate than WooCommerce's destination-based lookup since we were looking at the store's city and zip code, not the customer's city and zip code. We should always use the taxable address for looking up rates, similar to WooCommerce, to ensure we always update the same rate WooCommerce is using for internal total calculations. Using the same rate ensures the grand total always reflects the subtotal, shipping, and tax returned by TaxJar.
> Always Use Taxable Address for WC Rate Lookups

- includes/class-wc-taxjar-integration.php
This PR should accurately calculate sign-up fees with WooCommerce Subscriptions. To pass the sign-up fee amount to our API for tax calculations, we need to pull it directly using the `set_subscription_prices_for_calculation` method in `WC_Subscriptions_Cart`.
It should also fix related tax total issues by skipping calcs for the recurring totals cloned cart: https://wordpress.org/support/topic/woocommerce-subscriptions-tax-total-display-bug/
> WooCommerce Subscription Sign-Up Fees & Totals

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
Plugins such as [WooCommerce Product Bundles](https://woocommerce.com/products/product-bundles/) that allow merchants to create kits / bundled products can add duplicate line items with the same product ID in the cart. If this happens, our API can't differentiate between these line items and consolidates them. This results in a lower tax amount than expected.
This PR appends the cart item key to the line item ID and retains the product ID to determine the tax class when creating a new tax rate in WooCommerce.
> Sales Tax for Duplicate Line Items

- includes/class-wc-taxjar-integration.php
If a TaxJar user has "Debug Log" enabled in their configuration on a shared hosting plan, it's possible to receive "too many open files" server errors. Legacy code in our plugin was instantiating the WC_Logger for every `_log()` call which is bad. This PR ensures we only instantiate WC_Logger once if it isn't already set.
> Fix Potential Logging Issue on Shared Hosting

- includes/class-wc-taxjar-integration.php
This PR removes TaxJar's override of the default customer address so merchants can set it to geolocate if needed. Resolves #34
> Remove Default Customer Address Setting Override

- includes/class-wc-taxjar-nexus.php
- tests/specs/test-actions.php
This PR ensures the TaxJar plugin calculates sales tax when a user has their business location set to UK or Greece. SmartCalcs returns `UK` instead of `GB` and `EL` instead of `GR`. [Exceptions found here](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Imperfect_implementations).
> UK / Greece ISO 3166-1 Code Exceptions

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
Out of the box, WooCommerce has several default tax classes for VAT rates in the EU: Standard, reduced, and zero rates. As the name implies, the "Zero rate" tax class can be used for things such as VAT disability exemptions. Instead of requiring the user to rename this tax class to include the `99999` TaxJar exempt tax code, let's exempt it automatically.
This PR resolves issue #51.
> Zero Rate Tax Class Support

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
By default the TaxJar plugin disables "Round tax at subtotal level":
When we set the tax total in the cart, we should respect this setting and sum up the tax by line item instead. However, this change alone doesn't resolve rounding issues on the grand total. WC handles that calculation for us.
WC 3.2.5 wasn't properly rounding per line, so the spec attached to this PR won't pass. After [merging this PR](https://github.com/woocommerce/woocommerce/pull/18008), the spec passes and the rounding issue appears to be fully resolved. So once WC 3.2.6 or 3.3 is shipped we'll get this merged into the TaxJar plugin.
> Rounding Fix for Line Item Rounding in WC 3.2

- includes/class-wc-taxjar-integration.php
This PR fixes backend operations such as recalculating and saving orders when an order contains deleted products:
```
PHP Fatal error:  Uncaught Error: Call to a member function get_price() on boolean
```
> Fix Backend Error for Deleted Products

- includes/class-wc-taxjar-integration.php
In the current version of the TaxJar plugin (1.5.4 at the time of this note), the state and country values that TaxJar uses to calculate sales taxes are automatically pulled from the WooCommerce store address settings, and there is no way to change them.
In certain situations, a store owner's store address (as configured in the WooCommerce settings) is different than the address that needs to be used for TaxJar's calculations, leaving the store owner no choice but to change their store address in WooCommerce to get the TaxJar calculations to work.
This pull request adds a WordPress filter hook to the WC_Taxjar_Integration:get_store_settings() method return value, allowing the store owner to write a simple function that can override the store address settings without having to change their …
> Allows developers to override specific store setting values during runtime.

- includes/class-wc-taxjar-nexus.php
- tests/specs/test-class-taxjar-nexus.php
If a merchant's TaxJar API token becomes invalid or expired, excessive API calls were being made to `/v2/nexus/regions` to sync nexus addresses for each checkout calculation. This PR should fix the problem. For subsequent calculations, the nexus check will be skipped and the calculation request will still go through but it will return back an error.
Once we re-activate the API token in TaxJar, the merchant can manually refresh their nexus addresses from the TaxJar configuration screen inside WP admin.
**Specs passing in 2.6, 3.0, 3.1, 3.2, 3.3 🎉**
> Nexus API Overages

- tests/bootstrap.php
- tests/framework/product-helper.php
- tests/framework/shipping-helper.php
- tests/framework/woocommerce-helper.php
- tests/specs/test-actions.php
General improvements to specs from #61:
- New specs around exempt shipping and product exemption thresholds
- Use `WC()` function similar to Woo's native specs
- Drop `do_action` for `WC()->cart->calculate_totals()`
- Shipping helper class
- Tweak assert precision
> Spec Improvements

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
This PR resolves ongoing issues with recurring totals for subscription products between Woo 2.6 and 3.3. The `calculate_tax` method no longer uses class properties that can be modified by cloned carts in WooCommerce Subscriptions for recurring totals. A new method was introduced to calculate tax specifically for recurring totals without affecting the original totals. I also added some helper methods to get address and line item data before calculating tax.
> WooCommerce Subscriptions Refactor

- includes/class-wc-taxjar-integration.php
Fixes https://github.com/Automattic/woocommerce-services/issues/1433.
Skip API request when there aren't any line items - happens during recalculating taxes on an order where all products have been deleted.
> Skip API request when there are no line items.

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
This PR ensures products set to a "None" tax status with a custom product tax class containing a product tax code remain fully exempt. For example:
1) Set `None` tax status for a given product
2) Set `Clothing - 20010` or another custom tax class for the product
Our plugin should send a `99999` tax code for this product, not `20010`.
> Tax Code Precedence for Calculations

- includes/class-wc-taxjar-integration.php
Rather than skipping deleted products when performing backend calculations, this PR salvages line item data from the order to include the products in the API request. Resolves #68
> Backend Tax Calculations for Deleted Items

- includes/class-wc-taxjar-integration.php
From feedback on https://github.com/Automattic/woocommerce-services/pull/1435#issuecomment-396187342:
> The fix stops the invalid API requests. But when I created a product with price set to 0 and then selected a paid shipping options, there were no taxes requested for the shipping price.
> 
> This is because products with falsey price are not added to `$line_items`.
This PR conditionally includes `amount` or `line_items` as referenced in the documentation here: https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order
> Either `amount` or `line_items` parameters are required to perform tax calculations.
> Handle case where there aren’t order line items, but there are shipping charges.

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
This PR resolves a calculation issue with exemption thresholds on multiple line items sharing the same product tax class. For example, two clothing line items with one item over a given state threshold and another item below the threshold.
> Product Exemption Threshold Fix

- includes/class-wc-taxjar-integration.php
This PR checks the AJAX referrer when recalculating tax for backend orders in Woo 2.6 to avoid 403 forbidden errors. Regression introduced in #72.
1. Test in WooCommerce 2.6.13 or below.
2. Start a new order.
3. Add an item to the order and click "Save".
The item portion of the screen will stall unless this PR is applied.
> Fix Backend Order Calculations for Woo 2.6

- includes/class-wc-taxjar-integration.php
Our plugin currently hides the links to the native rate tables inside WooCommerce to prevent merchants from adding US-based rates and then having them overridden by our API. However, some merchants may want to collect tax in other countries we don't support yet or simply use their own rate without creating a nexus location in TaxJar. Exposing these rate tables allow them to do so.
To test, make sure the rate table links are shown in WooCommerce under **Settings > Tax**.
> Display Native Rate Tables for Custom Rates

- includes/class-wc-taxjar-integration.php
This PR resolves #80 to always call `woocommerce_after_calculate_totals` so other plugins can hook into the process immediately after tax is recalculated in the TaxJar plugin for WooCommerce 3.2+. Since we require discounts and additional data prior to making a sales tax API request and creating a native rate for WooCommerce's internal calculation process, we have to recalculate tax in WooCommerce again after creating the new tax rate and make sure we call the associated actions:
- woocommerce_before_calculate_totals
- woocommerce_after_calculate_totals
Test to make sure general calculations in 3.2+ continue to work. Specs passing.
> Call `woocommerce_after_calculate_totals` action for other plugins

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
This PR fixes local pickup method calculations for v2.0 of our plugin with street address support. When passing the street address, WooCommerce has a hard check for the location to have 4 parts (country, state, postal code, city) when looking up native tax rates. We need to hook into the `woocommerce_matched_rates` filter to support up to 5.
> Local Pickup Calculation v2.0 Fix

- includes/js/wc-taxjar-order.js
We intercept AJAX requests for backend orders to pass in a street address for rooftop accuracy. When a WooCommerce merchant manually creates a backend order with variable products using an unexpected variation label (such as a shoe size with special characters), `JSON.parse` can return an error and prevent the merchant from creating the order. This PR catches the error and allows the merchant to proceed.
1. Create a variable product with a variation name such as "2 1/4 x 3 1/2"
2. Start a new backend order
3. Add the variable product's variation to the order
4. Attempt to submit and create the order
After applying the PR, the browser should not show a `JSON.parse` error in the console and the merchant should be able to successfully create the …
> Catch JSON parsing errors for backend orders

- includes/class-wc-taxjar-integration.php
If a customer is VAT exempt, this PR removes taxes properly in Woo < 3.2. In later versions of Woo, if the customer is already exempt then `WC_Cart_Totals` should pick it up automatically via `get_is_vat_exempt`.
> Fix VAT exempt tax removal in Woo < 3.2

- includes/class-wc-taxjar-integration.php
This PR checks for the existence of `$this->settings['enabled']` and resolves #94.
> Check to make sure `enabled` setting exists

- tests/bootstrap.php
In the install.sh file it checks for an environmental variable (WP_TESTS_DIR) and if it is not set it then defaults to "/tmp/wordpress-tests-lib". However in the bootstrap.php file it is hardcoded to "/tmp/wordpress-tests-lib". This creates an issue when the environmental variable is already set, as it will install the files in the directory set in that environmental variable and then attempt to run them from the "/tmp/wordpress-tests-lib" directory.
This PR fixes the issue by using the same logic to set the WordPress tests directory in the bootstrap.php file as is in the install.sh file.
> Tweak specs to fully support environmental variables

- includes/class-wc-taxjar-connection.php
- includes/class-wc-taxjar-download-orders.php
- includes/class-wc-taxjar-integration.php
- taxjar-woocommerce.php
Over at WooCommerce Services, we are experimenting with integrating our plugins to work better together. Instead of porting the code over to our plugin we decided to try to add hooks that we could use to control the TaxJar plugin.
See https://github.com/Automattic/woocommerce-services/pull/1494 for how the new hooks are being used.
This PR proposes the following hooks:
* `taxjar_should_check_status` allows preventing the connection test request from being sent
* `taxjar_api_token_valid` overrides the API token validation
* `taxjar_can_connect` overrides the connection test result
* `taxjar_download_orders` overrides the value of the download orders option. [Combined with triggering the order validation on saving](https://github.com/Automattic/woocommerce-services/pull/1494/commits/c991c515 …
>  Add filters/actions allowing to override some of the plugin functions

- readme.txt
- taxjar-woocommerce.php
This PR indicates our plugin is tested up to WooCommerce 3.5 and WordPress 5.0.
1. Upgrade to WordPress 5.0
2. Upgrade to WooCommerce 3.5
3. Perform click-testing
All the things work in 3.5 💪
> Tested up to WooCommerce 3.5

- includes/class-wc-taxjar-integration.php
On the TaxJar settings page, the nexus regions will occasionally appear to be blank. This is occurring due to an issue in getting the nexus data when creating an order on the back-end of WooCommerce. When a user requests to calculate taxes for an order on the back-end, this is done through AJAX. The TaxJar plugin hooks into that AJAX request and attempts to run its tax calculations. If the transient containing the nexus data is not set or expired, it will run a request to TaxJar to pull in the nexus data. This is where the error occurs. When the TaxJar plugin is creating its request to get the nexus data, it calls a method that gets the TaxJar API token from either the $_POST variable or from the TaxJar settings. The logic it uses to determine which source to get the API token from is …
> Fix empty nexus list issue

- includes/class-wc-taxjar-integration.php
When running the TaxJar plugin with WooCommerce Smart Coupons installed, there was an issue where when the user used applied a gift card coupon and placed an order, the applied value of the gift card would go to zero (thus not reducing the amount the customer needed to pay) even though the gift cards value was still reduced by the order amount.
There is logic built into the WooCommerce Smart Coupons plugin that runs before WooCommerce calculates the totals for the cart. This logic checks to see if any gift cards have been applied and if so it prevents them from being applied again. This is in place to prevent a gift card from being double applied and it works great in normal circumstances.
However when run in combination with the TaxJar plugin it presents an issue. In order for tax to be …
> Add fix for compatibility with WooCommerce Smart Coupons

- includes/class-wc-taxjar-integration.php
There was an issue where when calculating the taxes for an order created on the backend, some products with an exempt tax class were still being taxed. This was caused by the method that pulled out the line items from the order. It would grab the tax class for each line item, for example clothing-rate-20010, and then it would attempt to pull out the TaxJar category ID from that string. However, the logic was built so that it explode the string into an array with the hyphen as the delimiter. It then always selected the second element in the array. In the example mentioned it selected `rate` instead of `20010`. Since the array element it selected was not an integer, it treated it as if there was no tax class when it made the request to the TaxJar API. 
This PR fixes the issue by altering …
> Fix exempt products getting taxed on back end

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
The TaxJar plugin works by sending both the store address as well as the ship to address to the TaxJar SmartCalcs API in order to the correct tax rates for each order. This occurs inside of WooCommerce's processes for calculating the order totals. While on the cart (in some themes) or checkout page, each time an end user updates their shipping information WooCommerce will recalculate the totals and cause an additional API request to SmartCalcs. There is already a caching of rates that occurs to help reduce the number of calls to the SmartCalcs API, however rates are only pulled from the cache when there is an exact match to an order (so all the shipping details have to perfectly match). In some themes and situations each character a user enters may cause WooCommerce to recalculate the …
> Validate zip codes before performing API requests

- tests/specs/test-actions.php
Due to rate changes in California, one of the specs was off. This PR fixes the spec to align with the new rates.
Note: Because this is just a change to the rates in a spec, there was no need to click test.
> Update California rates for specs

- tests/bootstrap.php
Previously, when setting up the unit tests, not all of the data was cleared out from the WooCommerce tables in the testing database. This caused sometime unexpected effects, including causing tests to fail when run in a group but pass successfully when run individually. This PR updates the bootstrap file in order to completely clear the database before reinstalling WooCommerce. This PR also eliminates an unnecessary call to the prepare_woocommerce helper function. There is no need to run it in the bootstrap file as it will be run when each test is setup.
The steps to reproduce the issues are inconsistent. However I was able to confirm the issue no longer occurred once the PR was applied.
1. Setup unit tests on a clean install
2. Run all unit tests
3. One unit test …
> Update bootstrap to completely clear woocommerce data from db before setting up specs

- includes/class-wc-taxjar-integration.php
When an order was being placed with larger number of exempt products in the cart, occasionally some of those exempt products where having tax applied to them. This was due to a floating point precision error in the override_woocommerce_tax_rates method. When comparing two floats using the == operator, it can return false on two seemingly the same doubles do to a different level of precision. This PR fixes the issue by using the round method to ensure the doubles being compared have the same level of precision. 
1. Create a product and add a tax exempt class to it (such as Clothing - 20010) 
2. Add a high quantity of the item to the cart (I was using a product that had a price of 14.95, and adding 14 of them to the cart would always replicate the error).
3. Check the …
> Fix floating point precision issue when handling exempt products

- includes/class-wc-taxjar-integration.php
The code replaced in this PR was originally added in order to ensure that when an order only contained fully exempt items, no tax was charged on the shipping for the order. However this code had been reported to cause issues with various shipping method plugins due to it overriding the cached shipping rates and setting them to null, which caused the shipping to have to be recalculated an extra time during the tax calculation. This PR fixes the issue by actually setting the cached shipping rate tax amount to $0 for fully exempt orders, rather than removing it and letting the shipping recalculate.
1. Enable TaxJar and USPS shipping
2. Create a USPS shipping rate and turn on debug mode, you also must make sure the rate is set to calculate shipping for the entire order …
> Pi 111 exempt shipping redundant calcs

- includes/class-wc-taxjar-integration.php
- includes/js/wc-taxjar-order.js
Previously, the customer id was not included when creating an order on the backend. This PR resolves the issue.
> Include Customer ID in Backend Order Tax Calculation

- includes/class-wc-taxjar-integration.php
This PR adds filters that enable merchants to alter the line item data before requests are sent to TaxJar. 
> Line Item Data Filters

- tests/framework/product-helper.php
- tests/framework/woocommerce-helper.php
- tests/specs/test-class-subscriptions.php
This PR adds support for WooCommerce 3.7
> WooCommerce 3.7 Support

- includes/class-wc-taxjar-integration.php
- tests/specs/test-actions.php
When placing orders outside of the US, there was an issue that occurred when the state field (can be called other names depending on the country) contained a space. An example of this is "West Sussex". When this is entered at checkout, the plugin would perform the API request to get the rates and insert them into WooCommerce's tax rate table. However when during the calculations, and we attempt to look up the rate in the table it would never be found. This is due to WooCommerce sanitizing the state field with the sanitize_key function when inserting the rate (which removes the space), but neglecting to do this during the rate lookup. This PR fixes the issue by performing the same sanitation before doing the lookup in the affected WooCommerce versions.
1. Add and …
> Tax Rate Lookup State Containing Space Fix

- CHANGELOG.md
- includes/abstract-class-taxjar-record.php
- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- includes/class-wc-taxjar-integration.php
- includes/class-wc-taxjar-transaction-sync.php
- readme.txt
- taxjar-woocommerce.php
- tests/framework/order-helper.php
- tests/specs/test-actions.php
- tests/specs/test-transaction-sync.php
This PR fixes a number of issues discovered in the beta:
1. Added hooks that allow order level exemptions to be set during calculations and during order / refund syncing.
2. Fixed issue where refunds created before an order was completed did not sync over to TaxJar.
3. Fixed issue where refunds with zero quantity line items failed to sync.
4. Added fallback for orders and refunds to billing address when shipping address is empty.
> Beta Version 3.0.1

- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- tests/specs/test-transaction-sync.php
Previously there was an issue that arose when attempting to sync an order or refund where one of the line items was from a product that no longer existed. This can occur because either the product was deleted after the order was placed or because the order was imported from a different system and so there was no corresponding product. This PR resolves the issue and also includes two additional specs to ensure the issue does not arise again.
1. Create an order and mark it completed
2. Delete a product from that order
3. Attempt to sync the product (the sync will fail and throw an error).
After applying the PR, in step 3 the sync will be successful.
> Fix record sync when product is non existant

- CHANGELOG.md
- includes/class-wc-taxjar-install.php
- includes/class-wc-taxjar-integration.php
- readme.txt
- taxjar-woocommerce.php
When upgrading the plugin to 3.0.0 or higher, and request was made to the TaxJar API to deregister to linked account in TaxJar. (Having the linked account is no longer necessary since orders are now pushed into TaxJar directly through the TaxJar API). When this deregistering occurred, some sites had differences between the store URL they used to register and the the store URL that was sent to deregister. This was due to usage of a different method for getting the store URL when deregistering than what was previously used in the plugin to register with TaxJar. This PR fixes that issue by ensuring that the store URL used to deregister is the same that was used to register.
1. Install TaxJar version 2.3.1 on a store where the "Site Address" and "WordPress Address" are …
> Deregistering From TaxJar APP

- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- includes/class-wc-taxjar-integration.php
- tests/specs/test-customer-sync.php
- tests/specs/test-transaction-sync.php
With new updates to the TaxJar API, some alphanumeric tax codes were introduced (previously all were numeric). In order to support these codes the numeric validation we performed on the tax class had to be removed.
> Remove Tax Code Numeric Validation

- includes/class-taxjar-refund-record.php
Hooks were added to the plugin previously that supported merchants changing the default order and refund IDs (post IDs). This was done to allow support for custom order ID plugins as well as to enable multiple woocommerce stores to use a single API Token. However when this was built the filter was missing from the reference ID that was synced on the order. This could have lead to refunds not tied to their original order. This PR fixes this by adding the correct filter.
> Add filter to reference id when syncing refunds

- CHANGELOG.md
- includes/abstract-class-taxjar-record.php
- includes/class-taxjar-order-record.php
- includes/class-wc-taxjar-install.php
- includes/class-wc-taxjar-integration.php
- includes/class-wc-taxjar-nexus.php
- includes/class-wc-taxjar-queue-list.php
- includes/class-wc-taxjar-record-queue.php
- readme.txt
- taxjar-woocommerce.php
- tests/specs/test-transaction-sync.php
The main issue that this PR resolves is fixing records that get stuck in awaiting status in the sync queue. This was happening due to a validation on the batch ID that caused it to not be able to be updated to 0 after a record failed to sync. Since the batch ID remained set to the initial batch ID that processed it, it would never get picked up and placed into another batch and so would stay stuck in the awaiting status.
This PR fixes the issue by altering the validation to allow the batch ID to be reset to 0. It also includes an update function that will run once upon updating and will located all of the records that meet this stuck condition and resolve their batch IDs to 0, allowing them to continue in the sync process.
This PR also includes various other improvements, such as:
- …
> Sync Queue Improvements

- taxjar-woocommerce.php
It was reported that our plugin was not loading the Action Scheduler library correctly, and it was causing issues with Action Scheduler availability when using WP CLI. Though I was unable to reproduce the issue we want to comply with with the recommended load order from Action Scheduler. This PR changes the load order to comply with their recommendation.
> Load action scheduler in correct order

- readme.txt
- taxjar-woocommerce.php
WooCommerce recently released version 3.8.0. After fully testing to verify compatibility, this PR updates the declared support in our plugin to this version.
> Update WooCommerce support to 3.8.0

- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- includes/class-wc-taxjar-transaction-sync.php
Currently the plugin only supports syncing orders that have completed or refunded status. Previously there were filters added to enable merchants to sync other statuses. However there is also a completed date validation that prevents orders that have never reached completed status from syncing. This prevented merchants from syncing orders with pending or other non complete statuses. This PR adds additional filters to allow merchants to bypass the date validation in these cases.
> Disable Date Validation Filters

- includes/class-wc-taxjar-install.php
- includes/class-wc-taxjar-queue-list.php
- includes/class-wc-taxjar-record-queue.php
- includes/class-wc-taxjar-transaction-sync.php
- taxjar-woocommerce.php
- tests/specs/test-customer-sync.php
- tests/specs/test-transaction-sync.php
Action Scheduler 3.0 changes how scheduled actions are stored in the database. Instead of being a custom post they are now stored in their own table. As part of this change they have limit the arguments field to 190 characters. Previously this was a longtext field used for storing a JSON string of the action arguments. With this change, TaxJar transaction sync batches with lots of orders would fail to migrate since their arguments JSON string was over the character limit. This would cause those batches to never run and sync to TaxJar.
In order to fix this we have changed our approach to using Action Scheduler. Instead of processing the queue and then running the transactions in batches in a later scheduled action, we have simplified our approach to process the queue and immediately begin …
> Action scheduler 3.0 fix

- .github/pull_request_template.md
- includes/class-wc-taxjar-ajax.php
- includes/class-wc-taxjar-integration.php
- includes/js/wc-taxjar-admin.js
- tests/bootstrap.php
Currently we have two ajax requests, to update nexus and to trigger a transaction backfill. Right now, neither the page that called the request or the permissons of the user are been validated. This means that there is the potential for anyone to be able to call these methods from outside of the site without having proper permissions.
This PR resolves the issue be creating security nonces that are loaded on the TaxJar settings page. These nonces are then send with the ajax requests and validated. This ensures that the ajax methods can only be called from those pages. This PR also validates the the current user has edit order permissions before the rest of the method runs.
This PR also includes a minor change to the load order when setting up the unit tests (necessary for testing on …
> Improve Security of Ajax Requests

- includes/class-wc-taxjar-integration.php
This PR updates the User Agent Header in TaxJar requests. This allows for easier and more consistent debugging.
> Update UA Header

- includes/class-wc-taxjar-integration.php
There are situations where the plugin's calculate tax method returns false (Vat exempt, not enough data to perform request to TaxJar, etc). In these situations unnecessary messages would be logged to the error log. There were also situations where unnecessary processing would occur. This PR resolves the issue by exiting the method when no tax is calculated through TaxJar.
1. Empty the error log
2. Create a VAT exempt customer
3. Add a product to the cart and go to cart/checkout so that the tax calculation is run.
4. Check error log to see unnecessary messages
After applying the PR, in step 4 there will no longer be any messages in the error log.
> Prevent unnecessary logging after calculating tax

- includes/class-wc-taxjar-connection.php
- includes/class-wc-taxjar-integration.php
- includes/css/admin.css
- includes/js/wc-taxjar-admin.js
Currently when setting up the plugin the user is required to navigate to the TaxJar app, get their API token, and then return to the plugin setting page to save the token and link their store with TaxJar. This PR provides a UI that allows the customer to simple click a connect button during setup, which will open a login to TaxJar, after signing in their API token will be automatically added and saved.
> SmartCalcs Connect

- includes/class-taxjar-order-record.php
When an order is created through the WooCommerce API and contains a fee, our plugin was not getting a value for the unit price when submitting the order to the TaxJar API. This caused the API request to fail and the order to not be synced to TaxJar. This PR resolves the issue but ensuring that if there is not an amount set on the fee, it will utilize the fee total.
1. Create an order containing a fee through the Woo API and mark the order as completed.
2. Manually trigger the sync queue to process
3.  Check the sync queue for the order created in step one, and there will be an error indicating the order could not sync due to mismatching order and line totals.
After applying the PR, in step 3 the order will have synced successfully.
**Click-Test …
> Fix no unit price of fee created through API issue

- includes/css/admin.css
- includes/js/wc-taxjar-admin.js
On older versions of the the WooCommerce plugin some of the smart calcs connect javascript and css were not working properly. This PR resolves the issue.
> Fix connect display with older woo versions

- taxjar-woocommerce.php
There is a bad link in the connection notification that appears when the TaxJar plugin has been installed but has not yet been connected to TaxJar. This PR fixes the link to go to the correct settings page.
1. Install TaxJar plugin
2. Click the link the in the connect to TaxJar notification
3. It will go to a settings page that does not exist 
After applying the PR, the link will take you to the correct settings page.
> Fix bad url in connect notification

- includes/class-wc-taxjar-integration.php
- tests/specs/test-transaction-sync.php
WooCommerce lowercases product tax code before storing them in the database. When the plugin pulls these codes to send them to TaxJar it uses the lowercased version which sometimes does not exactly match the TaxJar exemption code. This can cause products which should have been exempted to be taxed. This PR ensures the exemption code sent to TaxJar will match.
1. Create a tax class using the TaxJar giftcard exemption code (14111803A0001).
2. Apply this class to a product
3. Add the product to the cart and go to checkout. Tax will be calculated for the product
After applying the PR, in step 3 the product will be exempt from tax.
> Fix issue with tax codes being lowercased when sent to TaxJar API

- includes/abstract-class-taxjar-record.php
- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
An additional parameter was needed to identify requests within the TaxJar API. This parameter has now been added.
> Add plugin parameter to all transactions requests to TaxJar API

- includes/class-wc-taxjar-integration.php
_Describe the problem ([reference the issue](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) if applicable) and what the PR accomplishes._
Loading the TaxJar settings page with wp_debug enabled can generate notices for undefined array keys.  This PR checks if the array key exists before utilizing it.
1. Ensure php's error_reporting is set to E_ALL in php.ini and wp_debug is set to true 
2. Load the TaxJar settings page 
3. A PHP Notice is generated for undefined array keys
Loading the TaxJar settings page with wp_debug enabled generates zero notices.  
> Fix undefined index on TaxJar settings when wp_debug is enabled

- includes/class-wc-taxjar-integration.php
- tests/framework/class-tj-wc-rest-unit-test-case.php
- tests/specs/test-actions.php
- tests/specs/test-class-subscriptions.php
- tests/specs/test-customer-sync.php
In certain scenarios, when a cart has a reduced rate tax code and shipping is fully taxable, the shipping may not get taxed at the correct rate. This PR resolves this issue.
Also, Colorado was recently changed in TaxJar to have shipping not be taxable by default. This change broke some of the integration tests that tested the shipping tax on orders to Colorado. This PR fixes those integration tests.
The test_taxes_with_different_shipping_and_item_rates integration test simulates the scenario where the issue was occurring. Adding and then running this test in an older version of the integration will cause the test to fail (this can also be done on the front end of a store by using the address, store address and product data contained in the integration test). …
> INT-1043 Shipping Rate Fix

- includes/class-wc-taxjar-integration.php
- tests/specs/test-class-subscriptions.php
When there was a subscription product set up to have synchronized renewals with no trial period, on the cart page a message would display on the item indicating it contained a 1 month free trial.
After testing it was determined that the responsible portion of code was no longer needed. This PR resolves the issue by removing that code.
It also adds an expected deprecated annotation to some of the unit tests for subscriptions. This ensures the tests will be able to pass on the most recent versions of WooCommerce. There is no way to do deprecated annotations based on the version of WooCommerce we are testing against so this will cause those tests to fail on older versions of Woo until we build a new way to create subscription orders in the test suite.
1. Create a …
> Fix incorrect trial on synchronized renewals

- includes/abstract-class-taxjar-record.php
- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- tests/specs/test-transaction-sync.php
There is validation is place in order to prevent attempting to sync transactions to TaxJar, when the transactions have known missing or bad data. One of those validations is for the ship from address and it confirms that there is a country, state, city and zip code present before attempting to sync the transaction. This causes issues with international address that do not have states or provinces as they failed the validation.
This PR resolves the issue by only requiring the from state if the country is US or Canada. 
1. Set store settings to an international address with no state (UK address for example)
2. Place a test order
3. Manually sync the order. The sync will fail and the logs will have the message indicating a required ship from field is missing. …
> Fix international from address validation

- includes/class-wc-taxjar-nexus.php
- tests/specs/test-class-taxjar-nexus.php
There are scenarios where merchants may need to dynamically alter the nexus check logic. For instance adding additional international nexus areas. Currently there is no way for that to be accomplished. This PR adds a filter to allow these customizations. 
> Nexus Check Filter

- includes/class-wc-taxjar-transaction-sync.php
Previously, transaction sync required two settings for it to work, the sales tax calculation setting as well as the sales tax reporting setting. This was counter intuitive and made it so merchants couldn't sync transactions without also calculating sales tax. This PR resolves the issue by making transaction sync solely reliant on the sales tax reporting setting.
> Decouple tax calc and sync settings

- includes/class-taxjar-customer-record.php
- includes/class-wc-taxjar-customer-sync.php
- tests/specs/test-customer-sync.php
There were multiple issues regarding syncing exempt customers to TaxJar.
1. If the customer was missing a piece of required data (normally a name), it would fail to sync. Later if the data was added, it still would fail to sync unless one of the exemption settings was also changed.
This was fixed by falling back to use the user's username if no name was present. Also, the validation logic was altered so that any change to the user could trigger a sync to TaxJar, and only if all the data that is sent to TaxJar was identical as the last sync would syncing be skipped.
2. Tax exemptions would not save or sync unless the user creating the exemption had the manage_woocommerce capability. By default, this capability is only assigned to admins and store manager roles. In some circumstances stores …
> Exempt Customers Not Syncing Fix

- includes/class-wc-taxjar-integration.php
- tests/framework/woocommerce-helper.php
- tests/specs/test-class-subscriptions.php
- tests/specs/test-subscriptions.php
Previously there were periodic issues where PTCs were not being correctly applied to subscription and variable subscription products. This PR resolves the issues. 
It also includes a test to confirm full functionality in the future.
Note: This PR also includes a lot of changes to bring the changed files in line with our style guide. Comments will be added on the PR to indicate which changes are addressing the actual issue. I also recommend viewing the diff without showing whitespace differences.
1. Create a subscription variable product
2. At a PTC to that product
3. Add the product the cart and navigate to checkout. 
4. Check the tax calculation logs and see if the PTC is correctly sent to TaxJar.
5. You will see that the correct PTC was not sent to TaxJar
Note: …
> Subscription PTC Fix

- includes/class-wc-taxjar-ajax.php
- includes/class-wc-taxjar-transaction-sync.php
- includes/js/wc-taxjar-admin.js
There is a rare issue that occurs if a problem happens during plugin installation, that may cause the record queue database table to not be installed. In this case the user does not know there is an issue, however transaction sync will not ever work.
This PR fixes the issue by checking for this and adding an error message during backfill that indicates the problem and how to fix it.
1. Drop the record queue database table
2. Run transaction backfill (it needs to find at least one record to update).
3. A message will display indicating that records have been added to the queue, however the queue list view will be empty.
After applying the PR, the message should display that the database table was missing and give a suggestion for fixing it. …
> Handle non existent record queue table during transaction backfill

- includes/class-taxjar-api-request.php
- includes/class-taxjar-customer-record.php
- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- includes/class-wc-taxjar-ajax.php
- includes/class-wc-taxjar-connection.php
- includes/class-wc-taxjar-download-orders.php
- includes/class-wc-taxjar-integration.php
- includes/class-wc-taxjar-nexus.php
- taxjar-woocommerce.php
- tests/specs/test-class-taxjar-nexus.php
- tests/specs/test-filters.php
In order to ensure data sent to TaxJar for tax filings is as accurate as possible, the plugin needed to be updated to use a x-api-version header that has additional validation of transactions. As part of this change, the plugin was also improved by abstracting out the code used to perform requests to the TaxJar API. 
> X API Version Support

- includes/class-wc-taxjar-api-calculation.php
- includes/class-wc-taxjar-integration.php
- tests/framework/class-tj-wc-rest-unit-test-case.php
- tests/specs/test-actions.php
- tests/specs/test-api-calculation.php
The plugin currently calculates tax even for orders with a $0 total. This is not necessary. This PR stops the plugin from sending an API request to TaxJar when the order total is $0. This applies to orders created through the cart, in the dashboard, subscription renewals and orders created through the Woo REST API.
1. Place a order with a $0 total
2. Look in the logs and you will see an API request was sent to TaxJar.
After applying the PR, no API request will have been sent for those orders.
> Skip Tax Calc API Request For Zero Total Orders

- includes/class-wc-taxjar-integration.php
This issue was brought up in #178 
1. Create a subscription
2. Manually process the renew
3. Sales tax will be displayed twice on each line item of the subscription. (The totals will be correct but the sales tax should not be displayed twice).
After applying the PR, sales tax on each line item will only display once.
> Remove tax items before recalculating on subscriptions and API orders

- tests/bootstrap.php
- tests/framework/product-helper.php
- tests/specs/test-actions.php
There were multiple issues with our test specs and test framework. These included:
- A out of date spec that was failing due to changed rates.
- Subscription specs failing due to old method of creating subscription products.
- Warning messages about scripts being enqueue before the wp_enqueue_scripts action was fired.
This PR contains a rebuild of the way we create subscription products in the test framework, an update to the out of date spec and a fix to the warnings.
As the changes are only to the test suite, no click testing is necessary.
> Fixes for Test Suite

- includes/TaxCalculation/class-block-flag.php
- includes/class-taxjar-tax-calculation.php
- taxjar-woocommerce.php
- tests/specs/tax-calculation/test-block-flag.php
This PR enables our plugin to calculate tax when using the WooCommerce cart and checkout blocks.
1. Activate WooCommerce blocks plugin.
2. Add the cart/checkout block to a page.
3. Add a product to the cart and navigate to the page.
4. Tax will not be calculated.
After applying the PR, tax will be calculated in the cart and checkout blocks.
> Support WooCommerce Cart and Checkout Blocks

- includes/class-wc-taxjar-transaction-sync.php
This is a minor performance improvement to the transaction sync process. Transaction sync works using action scheduler. Every twenty minutes a scheduled action is run that will process all records in the queue and create/update them in TaxJar. If more records remain than a singe job can process, the action will be scheduled to run again at the next possible time. 
In addition to the queue processor there is also a method running on the "init" hook that ensures there is always a scheduled action to process the queue. This method exists because there have been occurrences of the scheduled action getting cancelled or removed and causing no transactions to sync to TaxJar. This PR moves that method from the "init" hook to the "admin_init" hook. This should reduce the number of queries …
> Minor performance optimization for transaction sync

- includes/TaxCalculation/class-order-tax-applicator.php
- includes/class-wc-taxjar-nexus.php
- tests/specs/tax-calculation/test-order-tax-applicator.php
This PR resolves the issues found in https://github.com/taxjar/taxjar-woocommerce-plugin/issues/193 and https://github.com/taxjar/taxjar-woocommerce-plugin/issues/192
When a customer set up their TaxJar account and did not configure any nexus states, the API response for nexus regions would return an empty list. When the nexus list was empty there was logic in our plugin that would determine that we should calculate tax for all orders. 
When the api response was returned for these orders, it would indicate that no nexus was found and would not include the "breakdown" field in the response. This scenario was not handled by the plugin and would lead to a fatal PHP error being thrown when attempting to apply the tax response to an order.
1. Create/use a TaxJar account …
> Fix error when no line items are present in tax details

- README.md
- composer.json
- composer.lock
- includes/class-taxjar-settings.php
- readme.txt
- taxjar-woocommerce.php
- tests/specs/tax-calculation/test-order-tax-applicator.php
- tests/specs/tax-calculation/test-tax-details.php
- tests/specs/test-actions.php
This PR address includes multiple fixes and improvements for the plugin. They are:
1. Update development dependencies.
2. Fix PHP errors when running test suite with PHP 7.4
3. Fix flakey spec due to rate change.
4. Fix risky spec discovered in new PHPUnit version
5. Fix PHP warning in admin when store address fields are not set
6. Update WordPress required version, PHP minimum version, WooCommerce minimum version WooCommerce tested up to version.
The test suite fixes can be tested by running the suite. All tests should pass with no failures, errors, etc.
To test the PHP warning in admin:
1. Enable WP_Debug
2. Remove the store address, city and zipcode on the WooCommerce Settings page and save the settings.
3. Go to the TaxJar settings page, the PHP warnings will be …
> INT 1954 Test Suite Fixes, Dependency Updates, Required Versions Updates

- includes/TaxCalculation/class-cart-tax-request-body-builder.php
- taxjar-woocommerce.php
- tests/bootstrap.php
- tests/framework/cart-builder.php
- tests/specs/tax-calculation/test-cart-tax-request-body-builder.php
The cart tax calculation portion of the plugin is built in such a way that it often creates conflicts with other plugins, and makes troubleshooting and maintenance difficult. This PR is the first step in resolving this issue. All the changes and fixes regarding the cart calculation process will be merged into and released with a feature branch.
> Add cart tax request body builder and tests

- includes/TaxCalculation/class-cart-tax-applicator.php
- includes/TaxCalculation/class-tax-builder.php
- tests/bootstrap.php
- tests/framework/abstract-cart-integration-test.php
- tests/framework/order-builder.php
- tests/integration/test-subscription-cart-tax-calculation.php
- tests/phpunit.xml
- tests/specs/test-subscriptions.php
This PR adds integration tests confirming the compatibility of the new cart calculation functionality with WooCommerce Subscriptions. It also fixes a minor issue where a subscription product was not having tax calculated on the correct price.
> INT 2039 Subscription Support

- CHANGELOG.md
- includes/TaxCalculation/class-tax-builder.php
- readme.txt
- taxjar-woocommerce.php
When save tax rates is enabled, the plugin should create a rate when applying tax to line items, fees, shipping, etc. It should not use the dynamic rate (which should only be used when the save rates setting is disabled). However there was an issue where the dynamic rate was still being applied when shipping wasn't taxable. It was still applying and calculating the correct amount of tax but was assigning the shipping item tax the dynamic rate ID.
This has been resolved. When shipping is not taxable, no tax rate will be applied to the shipping item. This brings the plugin inline with the WooCommerce native functionality.
Additionally in some stores, integrations were unable to handle the dynamic rate ID (999999999999999). This was due to them attempting to parse the ID as a int instead of …
> Fix dynamic tax code issues

- includes/TaxCalculation/class-cart-tax-calculation-result-data-store.php
- includes/TaxCalculation/class-order-tax-calculation-result-data-store.php
- includes/TaxCalculation/class-tax-calculator-builder.php
- includes/TaxCalculation/class-tax-calculator.php
- includes/class-taxjar-tax-calculation.php
- includes/interfaces/class-tax-calculation-result-data-store.php
- taxjar-woocommerce.php
- tests/specs/tax-calculation/test-cart-tax-result-data-store.php
- tests/specs/tax-calculation/test-order-tax-calculator.php
- tests/specs/tax-calculation/test-order-tax-result-data-store.php
In order to allow merchants to have more visibility into if and when TaxJar calculated tax on a cart/order and why we may not have calculated tax (for instance no nexus, etc.) we want to surface the tax calculation results to the order page in WooCommerce admin. This PR represents the first step to accomplish that.
This PR stores a JSON representation of the calculation results on the cart during the checkout process (and on recurring carts as well). When an order is created from a cart or a subscription is created from a recurring cart during checkout the JSON representation is then saved to the order/subscription as meta data.
> Save Calculation Results to Cart and Order

- includes/class-taxjar-tax-calculation.php
- tests/specs/test-get-tax-code.php
- tests/specs/test-transaction-sync.php
The TaxJar plugin parses PTCs (Product Tax Codes) from a given products tax class. These tax classes are natively functionality to WooCommerce which means that many invalid codes are sent to TaxJar when creating transactions. While this doesn't prevent the transaction from being created, it can create confusion for customers and potential confusion for filings.
This PR adds additional filtering to PTC parsing and ensures that only PTCs that are in a valid format are sent to TaxJar.
> Filter Invalid PTCs

- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
For some PHP configurations using json_encode on float values may caused them to be altered from their original state. For example 472.185 would become 472.18500000000006 after it has been encoded. This may create a scenario when the numbers are parsed in TaxJar that the math between the line item amounts and the total amounts do not add up correctly.
To resolve the issue all the floats are being cast as strings before performing the request to TaxJar.
> Fix Precision Point Issues When Creating Transactions in TaxJar

- includes/admin/class-admin-meta-boxes.php
- includes/admin/class-order-meta-box.php
- includes/admin/views/html-order-meta-box.php
- includes/class-wc-taxjar-integration.php
- includes/css/admin.css
- includes/js/wc-taxjar-order.js
- taxjar-woocommerce.php
This PR introduces a meta box on orders in the admin dashboard. This meta box surfaces data from the TaxJar calculation and sync processes. This includes:
- The calculation status of the order. Whether or not TaxJar calculated tax on the order in realtime, and if not the reason why.
- The sync status of the order. If the order has been synced to TaxJar and the last sync time.
- Additional meta data. This includes the JSON request and response from the calculation process.
> Admin Order Meta Box

- includes/TaxCalculation/class-cart-tax-calculation-result-data-store.php
- includes/TaxCalculation/class-order-tax-calculation-result-data-store.php
- includes/admin/class-order-meta-box.php
- includes/admin/views/html-order-meta-box.php
- includes/js/wc-taxjar-order.js
Previously in the logging feature branch we were storing the entire request and response JSON strings. It was determined that this approach may not scale well as these strings can be quite large and would be stored in the postmeta table for any order created. The storing and display of those values has now been removed.
> Calculation Logging Performance Changes

- CHANGELOG.md
- includes/TaxCalculation/class-cart-tax-calculation-result-data-store.php
- includes/TaxCalculation/class-order-tax-calculation-result-data-store.php
- includes/TaxCalculation/class-tax-calculator-builder.php
- includes/TaxCalculation/class-tax-calculator.php
- includes/abstract-class-taxjar-record.php
- includes/admin/class-admin-meta-boxes.php
- includes/admin/class-order-meta-box.php
- includes/admin/views/html-order-meta-box.php
- includes/class-taxjar-customer-record.php
- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- includes/class-taxjar-tax-calculation.php
- includes/class-wc-taxjar-integration.php
- includes/css/admin.css
- includes/interfaces/class-tax-calculation-result-data-store.php
- includes/js/wc-taxjar-order.js
- readme.txt
- taxjar-woocommerce.php
- tests/specs/tax-calculation/test-cart-tax-result-data-store.php
- tests/specs/tax-calculation/test-order-tax-calculator.php
- tests/specs/tax-calculation/test-order-tax-result-data-store.php
- tests/specs/test-transaction-sync.php
This PR adds a feature that displays the calculation and transaction sync statuses, any associated errors, etc. in a meta box on the admin order view.
It also includes a minor fix to remove the usage of the deprecated is_ajax function and the versioning bump to version 4.1.0.
> Calculation/Transaction Sync Status Meta Box

- includes/TaxCalculation/class-cart-tax-applicator.php
This PR adds action after Taxjar completes the cart totals calculation, as requested in #215 
Closes #215 
n/a
After applying the PR, other plugins can utilize added action and make it compatible with this plugin.
> enhancement/215: Added action after cart calculate totals

- includes/abstract-class-taxjar-record.php
- includes/class-taxjar-customer-record.php
- includes/class-taxjar-order-record.php
- includes/class-taxjar-refund-record.php
- includes/class-wc-taxjar-customer-sync.php
- includes/class-wc-taxjar-transaction-sync.php
This PR adds support for syncing customers to TaxJar in some common scenarios that weren't previously handled. This includes syncing a customer to TaxJar when the customer is created or updated through the WooCommerce REST API and when a customer is created or updated through the WooCommerce Customer/Order/Coupon CSV Import Suite.
> Add support for customer sync with REST API and Import Suite

- includes/class-taxjar-order-record.php
- includes/class-wc-taxjar-integration.php
- includes/compatibility/abstract-class-module.php
- includes/compatibility/class-module-loader.php
- includes/compatibility/modules/class-woocommerce-gift-cards.php
- includes/compatibility/modules/class-woocommerce-smart-coupons.php
- taxjar-woocommerce.php
This PR adds a new abstraction layer for compatibility modules. This makes it easier to maintain support for other plugins. Additionally a module was added for the WooCommerce Gift Cards plugin to resolve a conflict.
1. Create an order and use a gift card for a portion of the payment.
2. Complete the order and attempt to sync it to TaxJar
3. The order will fail to sync and the logs will indicate that the amount did not match the line items.
After applying the PR, the order will successfully sync.
> Add compatibility module for WooCommerce Gift Cards plugin

- includes/TaxCalculation/class-cart-tax-applicator.php
This PR adds refactors shipping tax application to resolve double-taxation issue on packages cause by the same shipping method being present in session more than once.
- Add simple taxable product to cart
- Navigate to checkout page to trigger tax calculation
- Observe calculated tax value is inflated
After applying the PR, package-index will be used to retrieve shipping method from session, avoiding duplicate tax application.
> Refactor cart shipping method tax application

- includes/TaxCalculation/class-cart-tax-applicator.php
- includes/TaxCalculation/class-order-tax-applicator.php
- includes/TaxCalculation/class-rate-manager.php
- includes/TaxCalculation/class-tax-builder.php
- includes/TaxCalculation/class-tax-details.php
- tests/specs/tax-calculation/test-tax-builder.php
This PR resolves https://github.com/taxjar/taxjar-woocommerce-plugin/issues/221. 
The TaxJar API returns an amount to collect for each line item. This amount to collect is used to apply tax to line item total (after discounts have been applied). Tax must also be applied to the line item subtotal (prior to discounts). In order to get the amount to apply to the subtotal, an "applied rate" is determined by dividing the amount collectable by the line item total. This rate was then applied to the subtotal.
When the setting was enabled to save tax rates into the WooCommerce tax rate table, a rate was then created using the "applied rate". This rate overwrote the rate created while applying tax to the line total, and would be slightly different than the actual rate returned by the TaxJar API.
In …
> Separate persisting woo rates from tax application

- includes/class-taxjar-order-record.php
When WooCommerce calculates the subtotal or total of a cart, it first rounds the line item subtotals/totals and then sums them. However it still will store the unrounded subtotal/total of each line.
In an edge case, when a line subtotal uses a higher level of precision then the precision set in the WooCommerce settings, it may prevent a transaction from syncing to TaxJar with the error: "amount must be equal to the sum of line items and shipping, excluding sales tax". This is due to our plugin not rounding the higher precision subtotal before using it to determine the unit price in the transaction request to TaxJar.
For example, an order has two line items with subtotals of 10.005 and a precision set to two decimal places. When WooCommerce calculates the order subtotal it will first round …
> Fix transaction sync issue regarding line subtotal precision

- includes/compatibility/class-module-loader.php
- includes/compatibility/modules/class-woocommerce-pdf-product-vouchers.php
- taxjar-woocommerce.php
This PR resolves the incorrect totals in cart while using the TaxJar and WooCommerce PDF Product Vouchers plugins as reported in https://github.com/taxjar/taxjar-woocommerce-plugin/issues/228.
1. Add an item to the cart and apply a multi use product voucher to the cart.
2. The totals will be incorrect as the voucher won't be factored into the total.
After applying the PR, the totals will be as expected.
> Fix conflict with WooCommerce PDF Product Vouchers plugin

- includes/TaxCalculation/class-order-tax-request-body-builder.php
Subscriptions created prior to TaxJar being enabled would not use the TaxJar PTC when added after subscription creation.  This PR resolves the issue by pulling the tax class directly from the product when possible.
1. Create a subscription using a product without a TaxJar PTC, and process a renewal. The TaxJar logs will show no PTC sent to the TaxJar API.
2. Change the product to use a TaxJar PTC. 
3. Process another renewal order. The logs will still show no PTC was sent in the calculation request.
After applying the PR, in step 3 the logs will show the newly added PTC was used in the calculation request.
> Get order tax class from product over line item

- CHANGELOG.md
- readme.txt
- taxjar-woocommerce.php
Updates compatible versions and latest tested version of WooCommerce and WordPress. 
WordPress is tested with version 6.3.1.
> Version 4.2.1

- includes/admin/class-admin-meta-boxes.php
- includes/class-wc-taxjar-integration.php
- readme.txt
**This PR:**
- Fixes a bug where the tax would still be calculated for an exempt customer if the order was created by and admin and HPOS was active
- Fixes a secondary bug, where the TaxJar meta boxes would not be displayed in each order's individual page if HPOS was active
- Fixes a small inconsistency in the readme.txt file, which was introduced in version 2.1.0. The [Changelog](https://wordpress.org/plugins/taxjar-simplified-taxes-for-woocommerce/#developers) section does not have the release version section headers bold since then.
1. Go to WordPress admin -> WooCommerce -> Settings -> Advanced -> Features -> enable HPOS
2. Go to Users -> Select a user -> and set the Exemption Type to 'Government'
3. Go to Orders -> Add order -> Select the user mentioned above, …
> Fix for two HPOS related issues and a small improvement for the readme

- includes/admin/class-admin-meta-boxes.php
- includes/admin/class-order-meta-box.php
**This PR:**
- Adds a fix for the issue number [#258](https://github.com/taxjar/taxjar-woocommerce-plugin/issues/258)
**Steps to reproduce**
- Go to WordPress admin -> WooCommerce -> Settings -> Advanced -> Features -> enable HPOS
- Go to an admin product page and scroll to the bottom of the page
- The TaxJar metabox not being displayed, as this is not an order page
**After applying the PR, this should happen.**
- The TaxJar metabox will be displayed only for the order pages
> #258 Stop displaying the metabox when the order can't be found

- CHANGELOG.md
- readme.txt
- taxjar-woocommerce.php
* RUN_TJPLAT-1732 - Fix test failures
* #258 Stop displaying the metabox when the order can't be found
> Release 4.2.3

- includes/class-wc-taxjar-integration.php
- tests/bootstrap.php
- tests/framework/woocommerce-helper.php
- tests/specs/test-actions.php
- tests/specs/test-customer-sync.php
- tests/specs/test-subscriptions.php
- Add explicit property declarations to prevent dynamic property warnings:
- Add $plugin_dir property to TaxJar_WC_Unit_Tests_Bootstrap class
- Add $log property to WC_Taxjar_Integration class
- Add $tj property to TJ_WC_Actions test class
- Fix WooCommerce Subscriptions file loading with existence check in bootstrap.php to prevent file not found warnings
- Replace problematic shipping total assignments with proper WooCommerce methods:
- Replace WC()->shipping->shipping_total = X with WC()->cart->set_shipping_total(X)
- Remove redundant shipping_total assignment in woocommerce-helper.php
> Fix PHP 8.2+ dynamic property deprecation warnings

- includes/js/wc-taxjar-admin.js
As part of the latest Woo (10.2.2) and WP (6.8.3) version compatibility testing, found an issue with the taxjar connect flow. 
To my knowledge at least starting from Woo version 9.9.5, when you hit this connect button below it successfully opens up taxjar pop-up and fetches the token but it won't save the form. So it looks as if nothing happened. So, users might repeat the action multiple times but nothing happens. But if you check the api token through the "Edit Api Token" link then it's there. It works fine with the version 8.9.3. 
**Root cause:** This connect button works by clicking a hidden "Save" button after fetching the token. But that hidden button got disabled by default in newer Woo versions. So, after fetching the token, the form does not detect any change and the button stays …
> Fix taxjar connect flow issue due to UI changes in the new woo versions (9.9.5>=)
